version: '3'
services:
  bookfahrt:
    container_name: bookfahrt-dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file: dev.env
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 100000; do :; done"
  bkdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: dev.env

