// Code generated by entc, DO NOT EDIT.

package completion

const (
	// Label holds the string label denoting the completion type in the database.
	Label = "completion"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the completion in the database.
	Table = "completions"
)

// Columns holds all SQL columns for completion fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
