// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/wonesy/bookfahrt/ent/completion"
)

// Completion is the model entity for the Completion schema.
type Completion struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Completion) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case completion.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Completion", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Completion fields.
func (c *Completion) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case completion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Completion.
// Note that you need to call Completion.Unwrap() before calling this method if this Completion
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Completion) Update() *CompletionUpdateOne {
	return (&CompletionClient{config: c.config}).UpdateOne(c)
}

// Unwrap unwraps the Completion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Completion) Unwrap() *Completion {
	tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Completion is not a transactional entity")
	}
	c.config.driver = tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Completion) String() string {
	var builder strings.Builder
	builder.WriteString("Completion(")
	builder.WriteString(fmt.Sprintf("id=%v", c.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Completions is a parsable slice of Completion.
type Completions []*Completion

func (c Completions) config(cfg config) {
	for _i := range c {
		c[_i].config = cfg
	}
}
