name: Run unit tests
on: [push]
jobs:
  bookfahrt-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: go version
      - run: go mod download
      - run: go test -v ./api/...
