name: Run unit tests
on: [push]
jobs:
  bookfahrt-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.1'
      - uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: report.xml
      - run: go get -u github.com/jstemmer/go-junit-report
      - run: go version
      - run: go mod download
      - run: go test -v ./api/... 2>&1 | go-junit-report > report.xml
