name: Run unit tests
on: [push]
jobs:
  bookfahrt-unit-tests:
    runs-on: ubuntu-latest
    container: golang:1.17.7-buster
    steps:
      - run: ls
      - run: go mod download
      - run: go test ./...
