// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// Club is the predicate function for club builders.
type Club func(*sql.Selector)

// Completion is the predicate function for completion builders.
type Completion func(*sql.Selector)

// Genre is the predicate function for genre builders.
type Genre func(*sql.Selector)

// Invitation is the predicate function for invitation builders.
type Invitation func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
